[DEN-352] Create cps certificate
Edgio/terraform-provider-edgecast pull request #104
Opened 2022-08-12 02:45 UTC by ssaluja4

2022-08-12 17:29 UTC, wdawg33 requested changes

2022-08-12 17:29 UTC, wdawg33 commented on edgecast/resources/cps/certificate.go
> +	if err != nil {
This is duplicated below on line 412.

2022-08-12 17:29 UTC, wdawg33 commented on edgecast/resources/cps/certificate.go
> +		return nil, nil
Would this be an error condition where we should return an error instead, or do we envision this in a go right flow?

2022-08-12 17:29 UTC, wdawg33 commented on edgecast/resources/cps/certificate_test.go
> +
Can we add a unit test for expandDomains?

2022-08-12 17:29 UTC, wdawg33 commented on edgecast/resources/cps/certificate_test.go
> +			name:          "Error path - incorrect input type",
There are a couple of paths not covered in the go right and general error paths. expandOrganization tests the happy path for expandAdditionalContacts, but not the negative path. We can create a follow up ticket to add coverage if you believe we should cover the additional paths and want to merge this today still.

2022-08-12 17:57 UTC, stevenpaz requested changes

2022-08-12 17:57 UTC, stevenpaz commented on edgecast/resources/cps/certificate.go
> +			"domains": {
since the properties are listed as individual items in `main.tf`, I think it would be better for this to be `domain` instead of `domains`

2022-08-12 17:57 UTC, stevenpaz commented on examples/resources/edgecast_cps_certificate/resource.tf
> +		additional_contacts{
Similar to my other comment - singular `additional_contact`

2022-08-12 21:23 UTC, stevenpaz requested changes

2022-08-12 21:23 UTC, stevenpaz commented on examples/resources/edgecast_cps_certificate/resource.tf
> +	domains {
Examples need to be updated to `domain`

2022-08-12 22:30 UTC, stevenpaz approved these changes

2022-08-22 23:57 UTC, stevenpaz approved these changes

2022-08-23 18:58 UTC, merged