initial implementation
Edgio/terraform-provider-edgecast pull request #112
Opened 2022-09-09 23:18 UTC by stevenpaz

2022-09-12 21:54 UTC, wdawg33 requested changes

2022-09-12 21:54 UTC, wdawg33 commented on edgecast/resources/cps/certificate.go
> +	ns, errs := ExpandNotificationSettings(d.Get("notification_setting"))
Did you want to check for errs here and return an error?

2022-09-12 21:54 UTC, wdawg33 commented on edgecast/resources/cps/certificate.go
> +		return helper.DiagsFromErrors(errs)
We should SetId("") here. There are also a few other places in this function we should be as well if you want to add them..

2022-09-12 21:54 UTC, wdawg33 commented on edgecast/resources/cps/certificate.go
> +	//ns, errs := ExpandNotificationSettings(d.Get("notification_settings"))
Can remove this if it is to stay on line 50

2022-09-13 21:34 UTC, ssaluja4 approved these changes

2022-09-14 01:13 UTC, wdawg33 requested changes

2022-09-14 01:13 UTC, wdawg33 commented on edgecast/resources/cps/certificate_test.go
> +func TestExpandNotifSettings(t *testing.T) {
Should we cover the cases that return an error here?

2022-09-14 01:13 UTC, wdawg33 commented on edgecast/resources/cps/certificate.go
> +func GetStringFromMap(m map[string]any, key string) (string, bool) {
Are you planning to add unit tests for these functions in the future (or are they moving out of certificate.go into helper?)

2022-09-14 19:13 UTC, wdawg33 approved these changes

2022-09-14 19:27 UTC, merged